/**
 * Seed script — populates the database with mock data.
 * Run via: pnpm --filter @workspace/db seed
 */
import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "./schema";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set");
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema });

async function main() {
  console.log("🌱 Seeding database…");

  // ── Categories ─────────────────────────────────────────────────────────
  await db.delete(schema.notificationsTable);
  await db.delete(schema.dashboardStatsTable);
  await db.delete(schema.messagesTable);
  await db.delete(schema.ordersTable);
  await db.delete(schema.reviewsTable);
  await db.delete(schema.productsTable);
  await db.delete(schema.phoneSpecsTable);
  await db.delete(schema.storesTable);
  await db.delete(schema.categoriesTable);

  await db.insert(schema.categoriesTable).values([
    { id: "cat_smartphones", icon: "phone-portrait", color: "#2563EB" },
    { id: "cat_usedPhones", icon: "phone-portrait-outline", color: "#7C3AED" },
    { id: "cat_tablets", icon: "tablet-portrait", color: "#0891B2" },
    { id: "cat_smartwatches", icon: "watch", color: "#059669" },
    { id: "cat_airpods", icon: "headset", color: "#1C1C1E" },
    { id: "cat_earbuds", icon: "ear", color: "#DC2626" },
    { id: "cat_chargers", icon: "flash", color: "#D97706" },
    { id: "cat_powerbanks", icon: "battery-charging", color: "#16A34A" },
    { id: "cat_cases", icon: "shield-checkmark", color: "#9333EA" },
    { id: "cat_speakers", icon: "volume-high", color: "#EA580C" },
    { id: "cat_gaming", icon: "game-controller", color: "#E11D48" },
    { id: "cat_offers", icon: "pricetag", color: "#0EA5E9" },
    { id: "cat_spareparts", icon: "construct", color: "#64748B" },
  ]);
  console.log("  ✓ categories");

  // ── Stores ─────────────────────────────────────────────────────────────
  await db.insert(schema.storesTable).values([
    {
      id: "s1",
      nameAr: "موبايل وورلد",
      nameEn: "Mobile World",
      descriptionAr:
        "أكبر متجر للهواتف الذكية والإكسسوارات في القاهرة. نوفر أحدث الأجهزة بأسعار تنافسية مع ضمان أصلي.",
      descriptionEn:
        "Cairo's largest smartphone and accessories store. We offer the latest devices at competitive prices with official warranty.",
      logoColor: "#2563EB",
      logoInitial: "M",
      coverGradientFrom: "#1E3A8A",
      coverGradientTo: "#2563EB",
      rating: 4.8,
      reviewsCount: 1243,
      governorate: "القاهرة",
      city: "مدينة نصر",
      address: "12 Mostafa El-Nahas St, Nasr City, Cairo",
      addressAr: "١٢ شارع مصطفى النحاس، مدينة نصر، القاهرة",
      lat: 30.0626,
      lng: 31.3342,
      phone: "+201234567890",
      whatsapp: "+201234567890",
      facebook: "mobileworldeg",
      instagram: "mobileworldeg",
      website: "https://mobileworldeg.com",
      workingHours: "Mon–Sat: 10am – 10pm",
      workingHoursAr: "الإثنين–السبت: ١٠ص – ١٠م",
      isOpen: true,
      isVerified: true,
      productsCount: 342,
      categories: [
        "cat_smartphones",
        "cat_usedPhones",
        "cat_tablets",
        "cat_cases",
        "cat_chargers",
      ],
    },
    {
      id: "s2",
      nameAr: "تك جالاكسي",
      nameEn: "Tech Galaxy",
      descriptionAr:
        "متخصصون في أجهزة سامسونج وملحقاتها الأصلية. خدمة عملاء ممتازة وضمان شامل على جميع المنتجات.",
      descriptionEn:
        "Samsung specialists with genuine accessories. Excellent customer service and full warranty on all products.",
      logoColor: "#1428A0",
      logoInitial: "T",
      coverGradientFrom: "#0F1E75",
      coverGradientTo: "#1428A0",
      rating: 4.6,
      reviewsCount: 867,
      governorate: "الإسكندرية",
      city: "المنتزه",
      address: "5 Abu Qir Rd, Montazah, Alexandria",
      addressAr: "٥ طريق أبو قير، المنتزه، الإسكندرية",
      lat: 31.2784,
      lng: 30.0172,
      phone: "+201098765432",
      whatsapp: "+201098765432",
      instagram: "techgalaxyalex",
      workingHours: "Daily: 9am – 11pm",
      workingHoursAr: "يومياً: ٩ص – ١١م",
      isOpen: true,
      isVerified: true,
      productsCount: 218,
      categories: [
        "cat_smartphones",
        "cat_tablets",
        "cat_smartwatches",
        "cat_earbuds",
      ],
    },
    {
      id: "s3",
      nameAr: "آيفون إيجيبت",
      nameEn: "iPhone Egypt",
      descriptionAr:
        "وجهتك الأولى لمنتجات آبل في مصر. نوفر أحدث هواتف آيفون والأكسسوارات الأصلية.",
      descriptionEn:
        "Your first destination for Apple products in Egypt. Latest iPhones and genuine Apple accessories.",
      logoColor: "#1C1C1E",
      logoInitial: "i",
      coverGradientFrom: "#1C1C1E",
      coverGradientTo: "#3A3A3C",
      rating: 4.9,
      reviewsCount: 2104,
      governorate: "القاهرة",
      city: "المعادي",
      address: "Road 9, Maadi, Cairo",
      addressAr: "شارع ٩، المعادي، القاهرة",
      lat: 29.9602,
      lng: 31.2569,
      phone: "+201555000111",
      whatsapp: "+201555000111",
      facebook: "iphoneegyptofficial",
      instagram: "iphoneegypt",
      website: "https://iphoneegypt.com",
      workingHours: "Mon–Thu, Sat: 10am – 9pm",
      workingHoursAr: "الإثنين–الخميس، السبت: ١٠ص – ٩م",
      isOpen: false,
      isVerified: true,
      productsCount: 156,
      categories: [
        "cat_smartphones",
        "cat_tablets",
        "cat_airpods",
        "cat_cases",
        "cat_chargers",
      ],
    },
    {
      id: "s4",
      nameAr: "سمارت هب الجيزة",
      nameEn: "Smart Hub Giza",
      descriptionAr:
        "متجر متكامل للهواتف والإكسسوارات في الجيزة. أسعار تنافسية وخدمة صيانة محترفة.",
      descriptionEn:
        "Complete phone and accessories store in Giza. Competitive prices and professional repair service.",
      logoColor: "#7C3AED",
      logoInitial: "S",
      coverGradientFrom: "#5B21B6",
      coverGradientTo: "#7C3AED",
      rating: 4.4,
      reviewsCount: 531,
      governorate: "الجيزة",
      city: "الدقي",
      address: "27 Tahrir St, Dokki, Giza",
      addressAr: "٢٧ شارع التحرير، الدقي، الجيزة",
      lat: 30.0444,
      lng: 31.2111,
      phone: "+201777888999",
      whatsapp: "+201777888999",
      instagram: "smarthubgiza",
      workingHours: "Daily: 10am – 10pm",
      workingHoursAr: "يومياً: ١٠ص – ١٠م",
      isOpen: true,
      isVerified: false,
      productsCount: 189,
      categories: [
        "cat_smartphones",
        "cat_usedPhones",
        "cat_speakers",
        "cat_gaming",
        "cat_cases",
      ],
    },
    {
      id: "s5",
      nameAr: "ميجا موبايل",
      nameEn: "Mega Mobile",
      descriptionAr:
        "أوسع تشكيلة من الإكسسوارات والهواتف في مصر. شحن سريع لجميع أنحاء الجمهورية.",
      descriptionEn:
        "Egypt's widest selection of accessories and phones. Fast shipping nationwide.",
      logoColor: "#DC2626",
      logoInitial: "M",
      coverGradientFrom: "#991B1B",
      coverGradientTo: "#DC2626",
      rating: 4.5,
      reviewsCount: 764,
      governorate: "القاهرة",
      city: "هليوبوليس",
      address: "Roxy Square, Heliopolis, Cairo",
      addressAr: "ميدان روكسي، مصر الجديدة، القاهرة",
      lat: 30.087,
      lng: 31.3356,
      phone: "+201122334455",
      whatsapp: "+201122334455",
      facebook: "megamobileeg",
      website: "https://megamobile.eg",
      workingHours: "Daily: 9am – 12am",
      workingHoursAr: "يومياً: ٩ص – ١٢م",
      isOpen: true,
      isVerified: true,
      productsCount: 512,
      categories: [
        "cat_chargers",
        "cat_powerbanks",
        "cat_cases",
        "cat_earbuds",
        "cat_speakers",
        "cat_spareparts",
      ],
    },
  ]);
  console.log("  ✓ stores");

  // ── Products ───────────────────────────────────────────────────────────
  await db.insert(schema.productsTable).values([
    {
      id: "p1",
      storeId: "s1",
      nameAr: "آيفون 16 برو ماكس",
      nameEn: "iPhone 16 Pro Max",
      descriptionAr:
        "أحدث إصدار من آبل بكاميرا ثلاثية متطورة ومعالج A18 Pro فائق الأداء.",
      descriptionEn:
        "Apple's latest flagship with advanced triple camera system and A18 Pro chip.",
      brand: "Apple",
      model: "iPhone 16 Pro Max",
      price: 89999,
      category: "cat_smartphones",
      condition: "new",
      inStock: true,
      warranty: "1 year",
      warrantyAr: "سنة واحدة",
      colors: ["#1C1C1E", "#E5E5E5", "#C4B5A5", "#4A4A4A"],
      storage: ["256GB", "512GB", "1TB"],
      ram: ["8GB"],
      imageColor: "#1C1C1E",
      rating: 4.9,
      reviewsCount: 342,
      isNew: true,
      isBestSeller: true,
      isFeatured: true,
    },
    {
      id: "p2",
      storeId: "s2",
      nameAr: "سامسونج جالاكسي S25 الترا",
      nameEn: "Samsung Galaxy S25 Ultra",
      descriptionAr:
        "قوة لا مثيل لها مع قلم S Pen مدمج وكاميرا 200 ميجابكسل.",
      descriptionEn:
        "Unrivaled power with built-in S Pen and 200MP camera system.",
      brand: "Samsung",
      model: "Galaxy S25 Ultra",
      price: 79999,
      discountPrice: 74999,
      category: "cat_smartphones",
      condition: "new",
      inStock: true,
      warranty: "1 year",
      warrantyAr: "سنة واحدة",
      colors: ["#1B1B1B", "#E7E1D7", "#5A6C5A", "#6B4F7A"],
      storage: ["256GB", "512GB", "1TB"],
      ram: ["12GB"],
      imageColor: "#1B1B1B",
      rating: 4.8,
      reviewsCount: 287,
      isNew: true,
      isBestSeller: true,
      isFeatured: true,
    },
    {
      id: "p3",
      storeId: "s3",
      nameAr: "آيفون 15",
      nameEn: "iPhone 15",
      descriptionAr: "أيفون 15 بشاشة سوبر ريتنا XDR وكاميرا 48 ميجابكسل رائعة.",
      descriptionEn:
        "iPhone 15 with Super Retina XDR display and impressive 48MP camera.",
      brand: "Apple",
      model: "iPhone 15",
      price: 52000,
      discountPrice: 48999,
      category: "cat_smartphones",
      condition: "new",
      inStock: true,
      warranty: "1 year",
      warrantyAr: "سنة واحدة",
      colors: ["#F9E5C8", "#4B89DC", "#3D9B63", "#F4C3C2", "#1C1C1E"],
      storage: ["128GB", "256GB", "512GB"],
      ram: ["6GB"],
      imageColor: "#4B89DC",
      rating: 4.7,
      reviewsCount: 198,
      isNew: false,
      isBestSeller: true,
      isFeatured: false,
    },
    {
      id: "p4",
      storeId: "s1",
      nameAr: "سامسونج جالاكسي A55",
      nameEn: "Samsung Galaxy A55",
      descriptionAr: "هاتف متوسط الفئة بمواصفات رائعة وتصميم أنيق.",
      descriptionEn: "Mid-range phone with premium specs and elegant design.",
      brand: "Samsung",
      model: "Galaxy A55",
      price: 22500,
      discountPrice: 19999,
      category: "cat_smartphones",
      condition: "new",
      inStock: true,
      warranty: "2 years",
      warrantyAr: "سنتان",
      colors: ["#1B3A6B", "#2D5A27", "#8B1A35", "#F0EFEB"],
      storage: ["128GB", "256GB"],
      ram: ["8GB", "12GB"],
      imageColor: "#1B3A6B",
      rating: 4.5,
      reviewsCount: 156,
      isNew: false,
      isBestSeller: false,
      isFeatured: true,
    },
    {
      id: "p5",
      storeId: "s4",
      nameAr: "جوجل بيكسل 9 برو",
      nameEn: "Google Pixel 9 Pro",
      descriptionAr:
        "تجربة كاميرا لا مثيل لها مع قدرات الذكاء الاصطناعي من جوجل.",
      descriptionEn: "Unmatched camera experience with Google AI capabilities.",
      brand: "Google",
      model: "Pixel 9 Pro",
      price: 58000,
      category: "cat_smartphones",
      condition: "new",
      inStock: true,
      warranty: "1 year",
      warrantyAr: "سنة واحدة",
      colors: ["#1A1A1A", "#F2E8DC", "#4A7B5C"],
      storage: ["128GB", "256GB", "512GB"],
      ram: ["16GB"],
      imageColor: "#1A1A1A",
      rating: 4.7,
      reviewsCount: 89,
      isNew: true,
      isBestSeller: false,
      isFeatured: true,
    },
    {
      id: "p6",
      storeId: "s5",
      nameAr: "شاومي 14 برو",
      nameEn: "Xiaomi 14 Pro",
      descriptionAr: "أداء فائق وشحن سريع 120 واط بسعر منافس.",
      descriptionEn:
        "Exceptional performance with 120W fast charging at a competitive price.",
      brand: "Xiaomi",
      model: "14 Pro",
      price: 38000,
      discountPrice: 34999,
      category: "cat_smartphones",
      condition: "new",
      inStock: true,
      warranty: "1 year",
      warrantyAr: "سنة واحدة",
      colors: ["#1C1C1C", "#F5F5F5", "#2D4A8A"],
      storage: ["256GB", "512GB"],
      ram: ["12GB", "16GB"],
      imageColor: "#2D4A8A",
      rating: 4.6,
      reviewsCount: 124,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
    },
    {
      id: "p7",
      storeId: "s3",
      nameAr: "آيربودز برو (الجيل الثاني)",
      nameEn: "AirPods Pro (2nd Gen)",
      descriptionAr: "أفضل سماعات لاسلكية مع إلغاء الضوضاء النشط.",
      descriptionEn:
        "Best-in-class wireless earbuds with active noise cancellation.",
      brand: "Apple",
      model: "AirPods Pro 2",
      price: 8500,
      discountPrice: 7999,
      category: "cat_airpods",
      condition: "new",
      inStock: true,
      warranty: "1 year",
      warrantyAr: "سنة واحدة",
      colors: ["#FFFFFF"],
      imageColor: "#E8E8E8",
      rating: 4.9,
      reviewsCount: 445,
      isNew: false,
      isBestSeller: true,
      isFeatured: true,
    },
    {
      id: "p8",
      storeId: "s1",
      nameAr: "كفر مغناطيسي آيفون 16",
      nameEn: "MagSafe Case iPhone 16",
      descriptionAr: "حماية كاملة مع دعم MagSafe للشحن اللاسلكي.",
      descriptionEn: "Full protection with MagSafe support for wireless charging.",
      brand: "Apple",
      model: "MagSafe Case",
      price: 1200,
      discountPrice: 999,
      category: "cat_cases",
      condition: "new",
      inStock: true,
      warranty: "6 months",
      warrantyAr: "٦ أشهر",
      colors: ["#1C1C1E", "#FFFFFF", "#DC2626", "#2563EB", "#7C3AED"],
      imageColor: "#2563EB",
      rating: 4.4,
      reviewsCount: 67,
      isNew: false,
      isBestSeller: false,
      isFeatured: false,
    },
  ]);
  console.log("  ✓ products");

  // ── Phone Specs ────────────────────────────────────────────────────────
  await db.insert(schema.phoneSpecsTable).values([
    {
      id: "ph1",
      brand: "Apple",
      model: "iPhone 16 Pro Max",
      os: "iOS 18",
      processor: "Apple A18 Pro",
      ram: ["8GB"],
      storage: ["256GB", "512GB", "1TB"],
      displaySize: '6.9"',
      displayType: "Super Retina XDR OLED",
      resolution: "2868 × 1320",
      refreshRate: "120Hz",
      brightness: "2000 nits",
      rearCamera: "48MP + 48MP + 12MP",
      frontCamera: "12MP",
      videoRecording: "4K 120fps",
      battery: "4685 mAh",
      charging: "45W",
      wirelessCharging: true,
      reverseCharging: false,
      fingerprint: false,
      faceUnlock: true,
      waterResistance: "IP68",
      weight: "227g",
      dimensions: "163.0 × 77.6 × 8.25mm",
      fiveG: true,
      nfc: true,
      bluetooth: "Bluetooth 5.3",
      wifi: "Wi-Fi 7",
      usb: "USB-C 3.2",
      audioJack: false,
      colors: ["Black", "White", "Desert", "Natural"],
      priceEGP: 89999,
      releaseDate: "Sep 2024",
      batteryMah: 4685,
      chargingW: 45,
      refreshRateHz: 120,
      rearMp: 48,
      ramGb: 8,
      displayInch: 6.9,
    },
    {
      id: "ph2",
      brand: "Samsung",
      model: "Galaxy S25 Ultra",
      os: "Android 15 (One UI 7)",
      processor: "Snapdragon 8 Elite",
      ram: ["12GB"],
      storage: ["256GB", "512GB", "1TB"],
      displaySize: '6.9"',
      displayType: "Dynamic AMOLED 2X",
      resolution: "3088 × 1440",
      refreshRate: "120Hz",
      brightness: "2600 nits",
      rearCamera: "200MP + 50MP + 10MP + 50MP",
      frontCamera: "12MP",
      videoRecording: "8K 30fps",
      battery: "5000 mAh",
      charging: "45W",
      wirelessCharging: true,
      reverseCharging: true,
      fingerprint: true,
      faceUnlock: true,
      waterResistance: "IP68",
      weight: "218g",
      dimensions: "162.8 × 77.6 × 8.2mm",
      fiveG: true,
      nfc: true,
      bluetooth: "Bluetooth 5.4",
      wifi: "Wi-Fi 7",
      usb: "USB-C 3.2",
      audioJack: false,
      colors: [
        "Titanium Black",
        "Titanium Silver Glow",
        "Titanium Whitesilver",
        "Titanium Pink Gold",
      ],
      priceEGP: 79999,
      releaseDate: "Jan 2025",
      batteryMah: 5000,
      chargingW: 45,
      refreshRateHz: 120,
      rearMp: 200,
      ramGb: 12,
      displayInch: 6.9,
    },
    {
      id: "ph3",
      brand: "Google",
      model: "Pixel 9 Pro",
      os: "Android 14",
      processor: "Google Tensor G4",
      ram: ["16GB"],
      storage: ["128GB", "256GB", "512GB"],
      displaySize: '6.3"',
      displayType: "LTPO OLED",
      resolution: "2992 × 1344",
      refreshRate: "120Hz",
      brightness: "3000 nits",
      rearCamera: "50MP + 48MP + 48MP",
      frontCamera: "10.5MP",
      videoRecording: "4K 60fps",
      battery: "4700 mAh",
      charging: "37W",
      wirelessCharging: true,
      reverseCharging: true,
      fingerprint: true,
      faceUnlock: true,
      waterResistance: "IP68",
      weight: "199g",
      dimensions: "152.8 × 72.0 × 8.5mm",
      fiveG: true,
      nfc: true,
      bluetooth: "Bluetooth 5.3",
      wifi: "Wi-Fi 7",
      usb: "USB-C 3.2",
      audioJack: false,
      colors: ["Obsidian", "Porcelain", "Hazel"],
      priceEGP: 58000,
      releaseDate: "Aug 2024",
      batteryMah: 4700,
      chargingW: 37,
      refreshRateHz: 120,
      rearMp: 50,
      ramGb: 16,
      displayInch: 6.3,
    },
    {
      id: "ph4",
      brand: "Xiaomi",
      model: "14 Pro",
      os: "Android 14 (HyperOS)",
      processor: "Snapdragon 8 Gen 3",
      ram: ["12GB", "16GB"],
      storage: ["256GB", "512GB"],
      displaySize: '6.73"',
      displayType: "LTPO AMOLED",
      resolution: "3200 × 1440",
      refreshRate: "120Hz",
      brightness: "3000 nits",
      rearCamera: "50MP + 50MP + 50MP",
      frontCamera: "32MP",
      videoRecording: "8K 24fps",
      battery: "4880 mAh",
      charging: "120W",
      wirelessCharging: true,
      reverseCharging: true,
      fingerprint: true,
      faceUnlock: true,
      waterResistance: "IP68",
      weight: "223g",
      dimensions: "161.4 × 75.3 × 8.5mm",
      fiveG: true,
      nfc: true,
      bluetooth: "Bluetooth 5.4",
      wifi: "Wi-Fi 7",
      usb: "USB-C 3.2",
      audioJack: false,
      colors: ["Black", "White", "Blue"],
      priceEGP: 38000,
      releaseDate: "Oct 2023",
      batteryMah: 4880,
      chargingW: 120,
      refreshRateHz: 120,
      rearMp: 50,
      ramGb: 16,
      displayInch: 6.73,
    },
    {
      id: "ph5",
      brand: "Samsung",
      model: "Galaxy Z Fold 6",
      os: "Android 14 (One UI 6.1.1)",
      processor: "Snapdragon 8 Gen 3",
      ram: ["12GB"],
      storage: ["256GB", "512GB", "1TB"],
      displaySize: '7.6" (main)',
      displayType: "Foldable Dynamic AMOLED 2X",
      resolution: "2160 × 1856",
      refreshRate: "120Hz",
      brightness: "2600 nits",
      rearCamera: "50MP + 10MP + 10MP",
      frontCamera: "10MP",
      videoRecording: "4K 60fps",
      battery: "4400 mAh",
      charging: "25W",
      wirelessCharging: true,
      reverseCharging: true,
      fingerprint: true,
      faceUnlock: true,
      waterResistance: "IPX8",
      weight: "239g",
      dimensions: "132.6 × 153.5 × 5.6mm (open)",
      fiveG: true,
      nfc: true,
      bluetooth: "Bluetooth 5.3",
      wifi: "Wi-Fi 7",
      usb: "USB-C 3.2",
      audioJack: false,
      colors: ["Pink", "Navy", "Silver Shadow", "White"],
      priceEGP: 110000,
      releaseDate: "Jul 2024",
      batteryMah: 4400,
      chargingW: 25,
      refreshRateHz: 120,
      rearMp: 50,
      ramGb: 12,
      displayInch: 7.6,
    },
    {
      id: "ph6",
      brand: "OnePlus",
      model: "13",
      os: "Android 15 (OxygenOS 15)",
      processor: "Snapdragon 8 Elite",
      ram: ["12GB", "16GB", "24GB"],
      storage: ["256GB", "512GB", "1TB"],
      displaySize: '6.82"',
      displayType: "LTPO AMOLED",
      resolution: "3168 × 1440",
      refreshRate: "120Hz",
      brightness: "4500 nits",
      rearCamera: "50MP + 50MP + 50MP",
      frontCamera: "32MP",
      videoRecording: "4K 60fps",
      battery: "6000 mAh",
      charging: "100W",
      wirelessCharging: true,
      reverseCharging: false,
      fingerprint: true,
      faceUnlock: true,
      waterResistance: "IP65",
      weight: "210g",
      dimensions: "162.9 × 76.0 × 8.9mm",
      fiveG: true,
      nfc: true,
      bluetooth: "Bluetooth 5.4",
      wifi: "Wi-Fi 7",
      usb: "USB-C 3.2",
      audioJack: false,
      colors: ["Black Eclipse", "Midnight Ocean", "Arctic Dawn"],
      priceEGP: 45000,
      releaseDate: "Jan 2025",
      batteryMah: 6000,
      chargingW: 100,
      refreshRateHz: 120,
      rearMp: 50,
      ramGb: 24,
      displayInch: 6.82,
    },
  ]);
  console.log("  ✓ phone specs");

  // ── Reviews ────────────────────────────────────────────────────────────
  await db.insert(schema.reviewsTable).values([
    {
      id: "r1",
      storeId: "s1",
      author: "Ahmed Mohamed",
      authorAr: "أحمد محمد",
      rating: 5,
      textAr:
        "خدمة ممتازة وأسعار معقولة جداً. الموظفون محترفون ومتعاونون. سأعود بالتأكيد!",
      textEn:
        "Excellent service and very reasonable prices. Staff is professional and cooperative. Will definitely return!",
      date: "2025-01-10",
    },
    {
      id: "r2",
      storeId: "s1",
      author: "Sara Hassan",
      authorAr: "سارة حسن",
      rating: 5,
      textAr:
        "اشتريت آيفون 16 من المتجر وكان التجربة رائعة. الجهاز أصلي 100% مع ضمان كامل.",
      textEn:
        "Bought an iPhone 16 from the store and had a great experience. The device is 100% genuine with full warranty.",
      date: "2025-01-08",
    },
    {
      id: "r3",
      storeId: "s2",
      author: "Mahmoud Ali",
      authorAr: "محمود علي",
      rating: 4,
      textAr: "متجر سامسونج موثوق. الأسعار مناسبة والخدمة احترافية. أنصح به بشدة.",
      textEn:
        "Reliable Samsung store. Fair prices and professional service. Highly recommended.",
      date: "2025-01-12",
    },
  ]);
  console.log("  ✓ reviews");

  // ── Dashboard seed data ────────────────────────────────────────────────
  await db.insert(schema.dashboardStatsTable).values([
    {
      storeId: "s1",
      views: 1850,
      visitors: 620,
      clicks: 310,
      reservations: 12,
      newReviews: 5,
      messagesCount: 28,
      saved: 95,
      trending: 4,
      date: "2026-07-14",
    },
  ]);

  await db.insert(schema.ordersTable).values([
    {
      id: "o1",
      storeId: "s1",
      productAr: "برو تك 14 الترا",
      productEn: "Pro Tech 14 Ultra",
      storage: "512GB",
      customer: "Sarah M.",
      timeAr: "منذ ساعتين",
      timeEn: "2 hrs ago",
      status: "PAID / RESERVED",
      price: 1099,
    },
    {
      id: "o2",
      storeId: "s1",
      productAr: "سامسونج S25 الترا",
      productEn: "Galaxy S25 Ultra",
      storage: "256GB",
      customer: "Ahmed K.",
      timeAr: "منذ ٤ ساعات",
      timeEn: "4 hrs ago",
      status: "RESERVED",
      price: 849,
    },
    {
      id: "o3",
      storeId: "s1",
      productAr: "آيفون 16 برو",
      productEn: "iPhone 16 Pro",
      storage: "128GB",
      customer: "Mona H.",
      timeAr: "منذ ٦ ساعات",
      timeEn: "6 hrs ago",
      status: "PENDING",
      price: 999,
    },
  ]);

  await db.insert(schema.messagesTable).values([
    {
      id: "m1",
      storeId: "s1",
      customer: "Sarah M.",
      productAr: "برو تك 14 الترا (512GB)",
      productEn: "Pro Tech 14 Ultra (512GB)",
      timeAr: "منذ ساعتين",
      timeEn: "2 hrs ago",
      status: "PAID / RESERVED",
      unread: 1,
    },
    {
      id: "m2",
      storeId: "s1",
      customer: "Ali Hassan",
      productAr: "سامسونج A55",
      productEn: "Samsung Galaxy A55",
      timeAr: "منذ يوم",
      timeEn: "1 day ago",
      status: "INQUIRY",
      unread: 0,
    },
  ]);
  console.log("  ✓ dashboard data");

  // ── Notifications ──────────────────────────────────────────────────────
  // "s1" doubles as the seller/store recipient id; "device_demo" stands in
  // for a buyer's persisted device UUID (see useDeviceId on mobile).
  const now = new Date();
  const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);

  await db.insert(schema.notificationsTable).values([
    {
      id: "notif_seed_1",
      userId: "s1",
      type: "new_order",
      titleAr: "طلب جديد",
      titleEn: "New Order",
      bodyAr: "لديك طلب جديد من سارة م. بقيمة 1099 د.أ",
      bodyEn: "You have a new order from Sarah M. worth $1099",
      metadata: { orderId: "o1" },
      readStatus: false,
      createdAt: hoursAgo(2),
    },
    {
      id: "notif_seed_2",
      userId: "s1",
      type: "review_received",
      titleAr: "تقييم جديد",
      titleEn: "New Review",
      bodyAr: "سارة حسن قيّمت متجرك بـ 5 نجوم",
      bodyEn: "Sara Hassan rated your store 5 stars",
      metadata: { reviewId: "r2", rating: 5 },
      readStatus: false,
      createdAt: hoursAgo(6),
    },
    {
      id: "notif_seed_3",
      userId: "s1",
      type: "new_message",
      titleAr: "رسالة جديدة",
      titleEn: "New Message",
      bodyAr: "سارة م: هل الجهاز لسه متاح؟",
      bodyEn: "Sarah M.: Is the device still available?",
      metadata: { customer: "Sarah M." },
      readStatus: true,
      createdAt: hoursAgo(26),
    },
    {
      id: "notif_seed_4",
      userId: "s1",
      type: "store_follow",
      titleAr: "متابع جديد",
      titleEn: "New Follower",
      bodyAr: "أحمد كريم بدأ متابعة متجرك",
      bodyEn: "Ahmed Kareem started following your store",
      metadata: null,
      readStatus: true,
      createdAt: hoursAgo(48),
    },
    {
      id: "notif_seed_5",
      userId: "device_demo",
      type: "order_status_updated",
      titleAr: "تحديث حالة الطلب",
      titleEn: "Order Status Updated",
      bodyAr: "تم تأكيد حجزك لجهاز برو تك 14 الترا",
      bodyEn: "Your reservation for Pro Tech 14 Ultra was confirmed",
      metadata: { orderId: "o1", status: "RESERVED" },
      readStatus: false,
      createdAt: hoursAgo(1),
    },
    {
      id: "notif_seed_6",
      userId: "device_demo",
      type: "favorite_price_change",
      titleAr: "انخفاض السعر",
      titleEn: "Price Drop",
      bodyAr: "انخفض سعر آيفون 16 برو في قائمة المفضلة لديك",
      bodyEn: "The price of iPhone 16 Pro in your favorites dropped",
      metadata: { productId: "p1" },
      readStatus: false,
      createdAt: hoursAgo(10),
    },
    {
      id: "notif_seed_7",
      userId: "device_demo",
      type: "promotional_campaign",
      titleAr: "عروض نهاية الأسبوع",
      titleEn: "Weekend Deals",
      bodyAr: "خصومات تصل إلى 20% على أفضل المتاجر هذا الأسبوع",
      bodyEn: "Up to 20% off top stores this weekend",
      metadata: null,
      readStatus: true,
      createdAt: hoursAgo(30),
    },
    {
      id: "notif_seed_8",
      userId: "device_demo",
      type: "system_announcement",
      titleAr: "تحديث جديد للتطبيق",
      titleEn: "App Update Available",
      bodyAr: "أضفنا مركز إشعارات جديد لمتابعة كل تحديثاتك في مكان واحد",
      bodyEn: "We added a new Notification Center to keep all your updates in one place",
      metadata: null,
      readStatus: true,
      createdAt: hoursAgo(72),
    },
  ]);
  console.log("  ✓ notifications");

  console.log("✅ Seed complete!");
  await pool.end();
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
